"""add vault tables

Revision ID: 9155c118c7c9
Revises: 37a4a7b8943e
Create Date: 2026-08-26 02:51:26.532043
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9155c118c7c9'
down_revision: Union[str, None] = '37a4a7b8943e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('possible', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_days_date'), 'vault_days', ['date'], unique=True)
    op.create_table('vault_block_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_day_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=20), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_day_id'], ['vault_days.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_day_id', 'block')
    )
    op.create_index(op.f('ix_vault_block_votes_vault_day_id'), 'vault_block_votes', ['vault_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_block_votes_vault_day_id'), table_name='vault_block_votes')
    op.drop_table('vault_block_votes')
    op.drop_index(op.f('ix_vault_days_date'), table_name='vault_days')
    op.drop_table('vault_days')
    # ### end Alembic commands ###
